[mgr]
ratio = [1, 4, 3]
title_format = "{cwd}"

sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false

linemode = "size"
scrolloff = 4
mouse_events = ["click", "scroll", "touch", "move"]

show_hidden = false
show_symlinks = true

[preview]
wrap = "no"
tab_size = 4
