theme = "onedark"

[editor]
line-number = "relative"

[editor.indent-guides]
render = true

[editor.whitespace]
render = "none"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
