# If not running interactively, don't do anything
[[ $- != *i* ]] && return

### SHOPT ###
shopt -s autocd         # change to named directory
shopt -s cdspell        # autocorrects cd misspellings
shopt -s cmdhist        # save multi-line commands in history as single line
shopt -s histappend     # do not overwrite history
shopt -s expand_aliases # expand aliases
shopt -s checkwinsize   # checks term size when bash regains control
shopt -s globstar       # use ** for recursive wildcard

bind "set completion-ignore-case on"

### PROMPT ###
# Using Nerd Fonts: "<current directory> <nf-md-chevron_triple_right> " all in green
export PS1=$'\[\033[1;32m\]\W \U000f0dbb \[\033[0m\]'

### ALIAS ###
alias   ..='cd ..'
alias  ...='cd ../..'
alias ....='cd ../../..'
alias   .4='cd ../../../..'
alias   .5='cd ../../../../..'

# Prefered format and colors
alias grep='grep --color=always'
alias ls='ls --color=always --group-directories-first -hv'
alias ip='ip --color=auto'
alias diff='diff --color=always -u'
alias less='less -R'
alias df='df -h'
alias ll='ls -l'
alias la='ls -lA'

# Better cat
alias cat='bat --theme="Visual Studio Dark+"'
alias icat='wezterm imgcat'

# Confirm before overwriting or deleting
alias rm='rm -iv'
alias mv='mv -iv'
alias cp='cp -iv'

### FUZZY STUFF ###

cdf() {
    cd $(find $1 -type d -not -path '*/[@.]*' | fzf)
}

dvim() {
    cdf $1 && nvim .
}

# Fuzzy find
alias fvim='nvim $(fzf)'

# Startup program
[[ -x $(command -v fastfetch) ]] && fastfetch
